# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_mitglied_beitrag_cent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitglied',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
