# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0003_auto_20210413_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastschriftmandat',
            name='mitglied',
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='beitrittsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitglied',
            name='telefon',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Lastschriftmandat',
        ),
    ]
