# Generated by Django 4.2.11 on 2024-08-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0006_auto_20240624_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mitglied',
            options={'ordering': ('mitgliedsnummer',), 'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
    ]
