# Generated by Django 4.2.23 on 2025-08-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0007_alter_mitglied_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitgliedskontobuchung',
            name='wirksam',
            field=models.BooleanField(default=True),
        ),
    ]
