# Generated by Django 4.2.23 on 2025-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0008_mitgliedskontobuchung_wirksam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitgliedskontobuchung',
            name='beleg_status',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
