# Generated by Django 4.2.23 on 2026-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umsaetze", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="umsatz",
            name="sortierhinweis",
            field=models.IntegerField(default=0),
        ),
    ]
