# Generated by Django 4.2.23 on 2025-08-10 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erinnerung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('titel', models.CharField(max_length=250)),
                ('erstmals', models.DateField(default=datetime.date.today)),
                ('zuletzt', models.DateField(default=datetime.date.today)),
                ('zyklus', models.CharField(choices=[('2Y', 'Zweijährig'), ('Y', 'Jährlich'), ('HY', 'Halbjährlich'), ('QY', 'Quartalsweise'), ('M', 'Monatlich'), ('4W', 'Vierwöchig')], default='Y', max_length=2)),
            ],
            options={
                'verbose_name': 'Erinnerung',
                'verbose_name_plural': 'Erinnerungen',
                'db_table': 'erinnerung',
            },
        ),
    ]
