# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitgliedschaftsantrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitgliedschaft', models.CharField(choices=[('O', 'Ordentliches Mitglied'), ('F', 'Fördermitglied')], default='O', max_length=2)),
                ('mitgliedsbeitrag', models.IntegerField(default=50)),
                ('antragsdatum', models.DateField(default=datetime.date.today)),
                ('vorname', models.CharField(max_length=250)),
                ('nachname', models.CharField(max_length=250)),
                ('anrede', models.CharField(blank=True, max_length=250)),
                ('geburtsdatum', models.DateField()),
                ('strasse', models.CharField(max_length=250)),
                ('adresszusatz', models.CharField(blank=True, max_length=250)),
                ('plz', models.CharField(max_length=10)),
                ('stadt', models.CharField(max_length=250)),
                ('land', models.CharField(default='Deutschland', max_length=250)),
                ('telefon', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('verifikationscode', models.CharField(max_length=250)),
                ('beruf', models.CharField(blank=True, max_length=250)),
                ('studienort', models.CharField(blank=True, max_length=250)),
                ('studienfach', models.CharField(blank=True, max_length=250)),
                ('mailingliste', models.BooleanField()),
                ('adresse_verein', models.BooleanField()),
                ('adresse_bwinf', models.BooleanField()),
                ('name_welt', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Mitgliedschaftsantrag',
                'verbose_name_plural': 'Mitgliedschaftsanträge',
                'db_table': 'mitgliedschaftsantrag',
            },
        ),
    ]
