# Generated by Django 4.2.11 on 2024-06-23 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitgliedsbeitrag_cent', models.IntegerField()),
                ('beschlussfassung', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Verein',
                'verbose_name_plural': 'Vereinsbeschlüsse',
                'db_table': 'verein',
            },
        ),
    ]
