# Generated by Django 2.2.28 on 2024-08-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0002_auto_20240624_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
