# Generated by Django 3.2.19 on 2025-04-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0003_auto_20240806_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
