# Generated by Django 4.2.23 on 2025-08-09 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0004_alter_verein_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freistellungsbescheid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finanzamt', models.CharField(max_length=250)),
                ('steuernummer', models.CharField(max_length=250)),
                ('zeitraum', models.CharField(max_length=250)),
                ('datum', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Freistellungsbescheid',
                'verbose_name_plural': 'Freistellungsbescheide',
                'db_table': 'freistellungsbescheid',
            },
        ),
        migrations.AddField(
            model_name='verein',
            name='vorstand1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='verein',
            name='vorstand2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='verein',
            name='mitgliedsbeitrag_cent',
            field=models.IntegerField(null=True),
        ),
    ]
