# Generated by Django 4.2.23 on 2025-08-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0005_freistellungsbescheid_verein_vorstand1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verein',
            name='mitgliedsbeitrag_cent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
