# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-13 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mitglieder', '0003_auto_20210413_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='GekuerztesLastschriftmandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontoinhaber', models.CharField(max_length=250)),
                ('anschrift', models.CharField(max_length=500)),
                ('bankname', models.CharField(max_length=250)),
                ('iban', models.CharField(max_length=250)),
                ('bic', models.CharField(max_length=250)),
                ('referenz', models.CharField(max_length=250)),
                ('erstellung', models.DateField(default=datetime.date.today)),
                ('unterschrift', models.DateField(default=None, null=True)),
                ('bestaetigung', models.DateField(default=None, null=True)),
                ('gueltig_ab', models.DateField(default=None, null=True)),
                ('gueltig_bis', models.DateField(default=None, null=True)),
                ('mitglied', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mitglieder.Mitglied')),
            ],
            options={
                'verbose_name': 'Gekürztes Lastschriftmandat',
                'verbose_name_plural': 'Gekürzte Lastschriftmandate',
                'db_table': 'gek_lastschriftmandat',
            },
        ),
    ]
