# Generated by Django 4.2.23 on 2025-08-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lastschriftmandatverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gekuerzteslastschriftmandat',
            name='entfernt',
            field=models.DateField(default=None, null=True),
        ),
    ]
